training_data = [
("@stellargirl loooooooovvvvvveee my Kindle2. Not that DX cool, 2 fantastic its own right.","positive"),
("Reading my kindle2...  Love it... Lee childs good read.","positive"),
("Ok, first assesment of #kindle2 ...it fucking rocks!!!","positive"),
("@kenburbary You'll love your Kindle2. I've had mine for few months never looked back. new big one huge! No need for remorse! :)","positive"),
("@mikefish  Fair enough. have Kindle2 think it's perfect  :)","positive"),
("@richardebaker no. too big. I'm quite happy with Kindle2.","positive"),
("Jquery my new best friend.","positive"),
("Loves twitter","positive"),
("how can you not love Obama? he makes jokes about himself.","positive"),
("House Correspondents dinner was last night whoopi, barbara &amp; sherri went, Obama got standing ovation","positive"),
("Watchin Espn..Jus seen thnew Nike Commerical with Puppet Lebron..sh*t was hilarious...LMAO!!!","positive"),
("#lebron best athlete of our generation, if not all time (basketball related) don't want get into inter-sport debates about   __1/2","positive"),
("i love lebron. http://bit.ly/PdHur","positive"),
("@Pmillzz lebron BOSS","positive"),
("@sketchbug Lebron hometown hero me, lol love Lakers let's go Cavs, lol","positive"),
("lebron zydrunas such an awesome duo","positive"),
("@wordwhizkid Lebron beast... nobody NBA comes even close.","positive"),
("downloading apps for my iphone! So much fun :-) There literally an app for just about anything.","positive"),
("good news, just had call from Visa office, saying everything fine.....what relief! am sick of scams out there! Stealing!","positive"),
("http://twurl.nl/epkr4b - awesome come back from @biz (via @fredwilson)","positive"),
("In montreal for long weekend of R&amp;R. Much needed.","positive"),
("Booz Allen Hamilton has bad ass homegrown social collaboration platform. Way cool!  #ttiv","positive"),
("[#MLUC09] Customer Innovation Award Winner: Booz Allen Hamilton -- http://ping.fm/c2hPP","positive"),
("@SoChi2 current use Nikon D90 love it, not as much as Canon 40D/50D. chose D90 for  video feature. My mistake.","positive"),
("@phyreman9 Google always good place look. Should've mentioned worked on Mustang w/ my Dad, @KimbleT.","positive"),
("RT @jessverr love nerdy Stanford human biology videos - makes me miss school. http://bit.ly/13t7NR","positive"),
("@spinuzzi: Has been bit crazy, with steep learning curve, LyX really good for long docs. For anything shorter, would be insane.","positive"),
("I'm listening \"P.Y.T\" by Danny Gokey &lt;3 &lt;3 &lt;3 Aww, he's so amazing. &lt;3 him so much :)","positive"),
("going sleep then on bike ride:]","positive"),
("@YarnThing you will not regret going see Star Trek. was AWESOME!","positive"),
("Highly recommend: http://tinyurl.com/HowDavidBeatsGoliath by Malcolm Gladwell","positive"),
("Blink by malcolm gladwell amazing book tipping point!","positive"),
("Malcolm Gladwell might be my new man crush","positive"),
("@robmalon Playing with Twitter API sounds fun.  May need take class or find new friend who like generate results with API code.","positive"),
("Hello Twitter API ;)","positive"),
("scrapbooking with Nic =D","positive"),
("RT @mashable: Five Things Wolfram Alpha Does Better (And Vastly Different) Than Google - http://bit.ly/6nSnR","positive"),
("just changed my default pic Nike basketball cause bball awesome!!!!!","positive"),
("Back when worked for Nike had one fav word : JUST DO IT! :)","positive"),
("By way, I'm totally inspired by thfreaky Nike commercial: http://snurl.com/icgj9","positive"),
("Class... 50d supposed come today :)","positive"),
("SHOUT OUTS ALL EAST PALO ALTO FOR BEING BUILDIN KARIZMAKAZE 50CAL GTA! ALSO THANKS PROFITS OF DOOM UNIVERSAL HEMPZ CRACKA......","positive"),
("@accann@edog1203 Great Stanford course. Thanks for making available public! Really helpful informative for starting off!","positive"),
("@ work til 6pm... lets go lakers!!!","positive"),
("omgg ohhdee want mcdonalds damn wonder if its open lol =]","positive"),
("@psychemedia really liked @kswedberg's \"Learning jQuery\" book. http://bit.ly/pg0lT worth look too","positive"),
("Very Interesting Ad from Adobe by Goodby, Silverstein &amp; Partners - YouTube - Adobe CS4: Le Sens Propre http://bit.ly/VprpT","positive"),
("Goodby Silverstein agency new site! http://www.goodbysilverstein.com/ Great!","positive"),
("RT @designplay Goodby, Silverstein's new site: http://www.goodbysilverstein.com/ enjoy it. *nice find!*","positive"),
("The ever amazing Psyop Goodby Silverstein &amp; Partners for HP! http://bit.ly/g2rU8 Have go play with After Effects now!","positive"),
("top ten most watched on Viral-Video Chart.  Love nike #mostvaluablepuppets campaign from Wieden &amp; Kennedy http://bit.ly/nR1n9","positive"),
("zomg!!! have G2!!!!!!!","positive"),
("Ok so lots of buzz from IO2009 how lucky - Free G2!! http://is.gd/Hyzl","positive"),
("just got free G2 android at google i/o!!!","positive"),
("Guess I'll be retiring my G1 start using my developer G2 woot #googleio","positive"),
("I am happy for Philip being at GoogleIO today","positive"),
("Lakers played great!  Cannot wait for Thursday night Lakers vs. ???","positive"),
("Judd Apatow creates fake sitcom on NBC.com market hnew movie... viral marketing at its best. http://is.gd/K0yK","positive"),
("watching Night at Museum . Lmao","positive"),
("i loved night at museum!!!","positive"),
("just got back from movies.  went see new night at museum with rachel.  was good","positive"),
("@shannyoday will take you on date see night at museum 2 whenever you want...it looks soooooo good","positive"),
("no watching Night At Museum. Getting Really Good","positive"),
("Night at Museum, Wolverine junk food - perfect monday!","positive"),
("saw night at museum 2 last night.. pretty crazy movie.. cast was awesome so was well worth it. Robin Williams forever!","positive"),
("My wrist still hurts. have get looked at. HATE dr/dentist/scary places. :( Time watch Eagle eye. If you want join, txt!","positive"),
("studing math ;) tomorrow exam dentist :)","positive"),
("Safeway very rock n roll tonight","positive"),
("i love Dwight Howard's vitamin water commercial... now wish he was with NIKE not adidas. lol.","positive"),
("lovin hNike  already that's only from running on spot hbedroom","positive"),
("@matthewcyan finally got around using jquery make my bio collapse. Yay for slide animations.","positive"),
("@PDubyaD right!!! LOL we'll get there!! have high expectations, Warren Buffet style.","positive"),
("RT @blknprecious1: RT GREAT @dbroos \"Someone's sitting shade today because someone planted tree long time ago.\"- Warren Buffet","positive"),
("Warren Buffet became (for time) richest man United States, not by working investing 1 Big idea which lead fortune","positive"),
("According create school, Notre Dame will have 7 receivers NCAA 10 at 84 or higher rating :) *sweet*","positive"),
("@BlondeBroad it's definitely under warranty &amp; my experience amazon support for kindle great! had contact them about my kindle2","positive"),
("We went Stanford University today. Got tour. Made me want go back college. It's also decided all of our kids will go there.","positive"),
("@ArunBasilLal love Google Translator too ! :D Good day mate !","positive"),
("reading on my new Kindle2!","positive"),
("My Kindle2 came LOVE it! :)","positive"),
("LOVING my new Kindle2.  Named her Kendra case u were wondering. \"cookbook\" tool cuz tells u all tricks!  Best gift EVR!","positive"),
("Obama quite good comedian! check out hdinner speech on CNN :) very funny jokes.","positive"),
("' Barack Obama shows hfunny side \" &gt;&gt; http://tr.im/l0gY !! Great speech..","positive"),
("I like thguy : ' Barack Obama shows hfunny side \" &gt;&gt; http://tr.im/l0gY !!","positive"),
("Obama's speech was pretty awesome last night! http://bit.ly/IMXUM","positive"),
("Reading  \"Bill Clinton Fail - Obama Win?\" http://tinyurl.com/pcyxj7","positive"),
("Obama More Popular Than U.S. Among Arabs: Survey: President Barack Obama's popularity leading Arab countries .. http://tinyurl.com/prlvqu","positive"),
("Obama's got JOKES!! haha just got watch bit of hafter dinner speech from last night... i'm love with mr. president ;)","positive"),
("it me or ththe best playoffs have been years oh yea lebron melo finals","positive"),
("@khalid0456 No, Lebron best","positive"),
("@the_real_usher LeBron cool.  like hpersonality...he has good character.","positive"),
("Watching Lebron highlights. Damn that niggas good","positive"),
("@Lou911 Lebron MURDERING shit.","positive"),
("@uscsports21 LeBron monsta he only 24. SMH world ain't ready.","positive"),
("@cthagod when Lebron done NBA he will probably be greater than Kobe. Like u said Kobe good there alot of 'good' players.","positive"),
("KOBE GOOD BT LEBRON HAS MY VOTE","positive"),
("@asherroth World Cup 2010 Access?? Damn, that's good look!","positive"),
("Just bought my tickets for 2010 FIFA World Cup South Africa. Its going be great summer. http://bit.ly/9GEZI","positive"),
("The great Indian tamasha truly will unfold from May 16, result day for Indian General Election.","positive"),
("@crlane have Kindle2. I've seen pictures of DX, haven't seen person. love my Kindle - I'm on everyday.","positive"),
("@criticalpath Such an awesome idea -  continual learning program with Kindle2  http://bit.ly/1ZLfF","positive"),
("@faithbabywear Ooooh, what model you getting??? have 40D LOVE LOVE LOVE LOVE it!","positive"),
("The Times of India: wonder that India's election. http://bit.ly/p7u1H","positive"),
("http://is.gd/ArUJ Good video from Google on using search options.","positive"),
("Stanford Charity Fashion Show top draw http://cli.gs/NeNuAH","positive"),
("Stanford University?s Facebook Profile One of Most Popular Official University Pages - http://tinyurl.com/p5b3fl","positive"),
("Lyx cool.","positive"),
("SOOO DISSAPOiNTED SENT DANNY GOKEY HOME... YOU STiLL ROCK ...DANNY ... MY HOMETOWN HERO !! YEAH MiLROCKEE!!","positive"),
("RT @PassionModel 'American Idol' fashion: Adam Lambert tones down, Danny Gokey cute ... http://cli.gs/7JWSHV","positive"),
("@dannygokey love you DANNY GOKEY!! :)","positive"),
("With my best girl for few more hours San francisco. Mmmmmfamily wonderful!","positive"),
("Went see Star Trek movie last night.  Very satisfying.","positive"),
("I can't wait, going see star trek tonight!!","positive"),
("Star Trek was as good as everyone said!!","positive"),
("am loving new malcolm gladwell book - outliers","positive"),
("I highly recommend Malcolm Gladwell's 'The Tipping Point.' My next audiobook will probably be one of has well.","positive"),
("RT @clashmore: http://bit.ly/SOYv7  Great article by Malcolm Gladwell.","positive"),
("I seriously underestimated Malcolm Gladwell.  want meet thdude.","positive"),
("I'm really loving new search site Wolfram/Alpha. Makes Google seem so ... quaint. http://www72.wolframalpha.com/","positive"),
("Off NIKE factory!!!","positive"),
("New nike muppet commercials pretty cute. Why do live together again?","positive"),
("@tonyhawk http://twitpic.com/5c7uj - AWESOME!!! Seeing show Friday at Shoreline Amphitheatre. Never seen NIN before. Can't wait. ...","positive"),
("@mitzs hey bud :) np do so love my 50D, although I'd love 5D mkII more","positive"),
("@jonduenas @robynlyn just got us 50D for office. :D","positive"),
("Just picked up my new Canon 50D...it's beautiful!!  Prepare for some seriously awesome photography!","positive"),
("Just got my new toy. Canon 50D. Love love love it!","positive"),
("Learning about lambda calculus :)","positive"),
("I'm moving East Palo Alto!","positive"),
("@ atebits just finished watching your Stanford iPhone Class session. really appreciate it. You Rock!","positive"),
("@jktweet Hi! Just saw your Stanford talk really liked your advice. Just saying Hi from Singapore (yes videos do get around)","positive"),
("LAKERS tonight let's go!!!!","positive"),
("Will Lakers kick Nuggets ass tonight?","positive"),
("Prettiest insects EVER - Pink Katydids: http://bit.ly/2Upw2p","positive"),
("Just had McDonalds for dinner. :D was goooood. Big Mac Meal. ;)","positive"),
("AHH YES LOL IMA TELL MY HUBBY GO GET ME SUM MCDONALDS =]","positive"),
("Stopped have lunch at McDonalds. Chicken Nuggetssss! :) yummmmmy.","positive"),
("Could go for lot of McDonalds. mean LOT.","positive"),
("my exam went good. @HelloLeonie: your prayers worked (:","positive"),
("Only one exam left, am so happy for :D","positive"),
("Absolutely hilarious!!! from @mashable:  http://bit.ly/bccWt","positive"),
("@mashable never did thank you for including me your Top 100 Twitter Authors! You Rock! (&amp; New Wave :-D) http://bit.ly/EOrFV","positive"),
("RT @shrop: Awesome JQuery reference book for Coda! http://www.macpeeps.com/coda/ #webdesign","positive"),
("I've been sending e-mails like crazy today my contacts...does anyone have contact at Goodby SIlverstein...I'd love speak them","positive"),
("Goodby, Silverstein's new site... http://www.goodbysilverstein.com/ enjoy it.","positive"),
("Wow everyone at Google I/O conference got free G2's with month of unlimited service","positive"),
("@vkerkez dood got free google android phone at I/O conference. G2!","positive"),
("@Orli G2 amazing btw, HUGE improvement over G1","positive"),
("HTML 5 Demos! Lots of great stuff come! Yes, I'm excited. :) http://htmlfive.appspot.com #io2009 #googleio","positive"),
("@googleio http://twitpic.com/62shi - Yay! Happy place! Place place!  love Google!","positive"),
("#GoogleIO | O3D - Bringing 3d graphics browser. Very nice tbh. Funfun.","positive"),
("Awesome viral marketing for \"Funny People\" http://www.nbc.com/yo-teach/","positive"),
("Night At Museum 2? Pretty furkin good.","positive"),
("Watching Night at Museum - giggling.","positive"),
("just watched night at museum 2! so stinkin cute!","positive"),
("So, Night at Museum 2 was AWESOME! Much better than part 1. Next weekend we'll see Up.","positive"),
("saw new Night at Museum loved it. Next go see UP 3D","positive"),
("yankees won mets lost. its good day.","positive"),
("My dentist appt today was actually quite enjoyable.","positive"),
("Just applied at Safeway!(: Yeeeee!","positive"),
("Nike rocks. I'm super grateful for what I've done with them :) &amp; European Division of NIKE BEYOND! @whitSTYLES @muchasmuertes","positive"),
("@evelynbyrne have you tried Nike  ? V. addictive.","positive"),
("The Nike Training Club (beta) iPhone app looks very interesting.","positive"),
("I'm ready drop pretenses, am forever love with jQuery, want marry it. Sorry ladies, thnerd jquery.spokenFor.js","positive"),
("SUPER INVESTORS: great weekend read here from Warren Buffet. Oldie, goodie. http://tinyurl.com/oqxgga","positive"),
("reading Michael Palin book, Python Years...great book. also recommend Warren Buffet &amp; Nelson Mandela's bio","positive"),
("I mean, I'm down with Notre Dame if have to.  It's good school, I'd be closer Dan, I'd enjoy it.","positive"),
("I'd say some sports writers idiots for saying Roger Federer one of best ever Tennis.  Roger Federer best ever Tennis","positive"),
("I love my Kindle2. No more stacks of books trip over on way loo.","positive"),
("GOT MY WAVE SANDBOX INVITE! Extra excited! Too bad have class now... I'll play with soon enough! #io2009 #wave","positive"),
("@sklososky Thanks so much!!! ...from one of your *very* happy Kindle2 winners ; ) was so surprised, fabulous. Thank you! Best, Kathleen","positive"),
("@cwong08 have Kindle2 (&amp; Sony PRS-500). Like it! Physical device feels good. Font nice. Pg turns snappy enuf. UI little klunky.","positive"),
("The #Kindle2 seems best eReader, will work UK where can get one?","positive"),
("I have google addiction. Thank you for pointing that out, @annamartin123. Hahaha.","positive"),
("Excited about seeing Bobby Flay Guy Fieri tomorrow at Great American Food &amp; Music Fest!","positive"),
("Gonna go see Bobby Flay 2moro at Shoreline. Eat drink. Gonna be good.","positive"),
("can't wait for great american food music festival at shoreline tomorrow.  mmm...katz pastrami bobby flay. yes please.","positive"),
("My dad was NY for day, ate at MESA grill last night met Bobby Flay. So much fun, except completely lost my voice today.","positive"),
("getting ready test out some burger receipes thweekend. Bobby Flay has some great receipes try. Thanks Bobby.","positive"),
("i lam so love with Bobby Flay... he my favorite. RT @terrysimpson: @bflay you need place Phoenix. have great peppers here!","positive"),
("using Linux loving - so much nicer than windows... Looking forward using wysiwyg latex editor!","positive"),
("After using LaTeX lot, any other typeset mathematics just looks hideous.","positive"),
("Ahhh... back *real* text editing environment. &lt;3 LaTeX.","positive"),
("Fuck theconomy. hate aig their non loan given asses.","negative"),
("@Karoli firmly believe that Obama/Pelosi have ZERO desire be civil.  It's charade slogan, want destroy conservatism","negative"),
("dear nike, stop with flywire. that shit waste of science. ugly. love, @vincentx24x","negative"),
("I was talking thguy last night he was telling me that he die hard Spurs fan.  He also told me that he hates LeBron James.","negative"),
("@ludajuice Lebron Beast, I'm still cheering 4 A..til end.","negative"),
("Played with an android google phone. slide out screen scares me would break that fucker so fast. Still prefer my iPhone.","negative"),
("US planning resume military tribunals at Guantanamo Bay... only thtime those on trial will be AIG execs Chrysler debt holders","negative"),
("omg so bored &amp; my tattoooos so itchy!!  help! aha =)","negative"),
("I'm itchy miserable!","negative"),
("@sekseemess no. I'm not itchy for now. Maybe later, lol.","negative"),
("cant sleep... my tooth aching.","negative"),
("Blah, blah, blah same old same old. No plans today, going back sleep guess.","negative"),
("glad didnt do Bay Breakers today, it's 1000 freaking degrees San Francisco wtf","negative"),
("?Obama Administration Must Stop Bonuses AIG Ponzi Schemers ... http://bit.ly/2CUIg","negative"),
("started think that Citi really deep s&amp;^t. gonna survive turmoil or gonna be next AIG?","negative"),
("ShaunWoo hate'n on AiG","negative"),
("annoying new trend on internets:  people picking apart michael lewand malcolm gladwell.  nobody wants read that.","negative"),
("omg. commercials alone on ESPN going drive me nuts.","negative"),
("@morind45 Because twitter api slow most client's aren't good.","negative"),
("yahoo answers can be butt sometimes","negative"),
("RT @SmartChickPDX: Was just told that Nike layoffs started today :-(","negative"),
("needs someone explain lambda calculus him! :(","negative"),
("Took Graduate Field Exam for Computer Science today.  Nothing makes you feel like more of an idiot than lambda calculus.","negative"),
("@legalgeekery Yeahhhhhhhhh, wouldn't really have lived East Palo Alto if could have avoided it.  guess it's only for summer.","negative"),
("Damn you North Korea. http://bit.ly/KtMeQ","negative"),
("Can just go ahead blow North Korea off map already?","negative"),
("North Korea, please cease thdouchebaggery. China doesn't even like you anymore. http://bit.ly/NeHSl","negative"),
("Why hell Pelosi freakin China? on whose dime?","negative"),
("Are YOU burning more cash $$$ than Chrysler GM? Stop financial tsunami. Where \"bailout\" means taking handout!","negative"),
("insects have infected my spinach plant :(","negative"),
("wish could catch every mosquito world n burn em slowly.they been bitin shit outta me 2day.mosquitos assholes of insects","negative"),
("just got back from church, totally hate insects.","negative"),
("Just got mcdonalds goddam those eggs make me sick. O yeah Laker up date go lakers. Not much of an update? Well it's true so suck it","negative"),
("History exam studying ugh","negative"),
("I hate revision, it's so boring! am totally unprepared for my exam tomorrow :( Things not looking good...","negative"),
("Higher physics exam tommorow, not lookin forward much :(","negative"),
("It's bank holiday, yet I'm only out of work now. Exam season sucks:(","negative"),
("Cheney Bush real culprits - http://fwix.com/article/939496","negative"),
("Life?s bitch? so Dick Cheney. #p2 #bipart #tlot #tcot #hhrs #GOP #DNC http://is.gd/DjyQ","negative"),
("Dick Cheney's dishonest speech about torture, terror, Obama. -Fred Kaplan Slate. http://is.gd/DiHg","negative"),
("\"The Republican party bunch of anti-abortion zealots who couldn't draw flies dump.\" -- Neal Boortz (just now, on radio)","negative"),
("Twitter's connections API broken? Some tweets didn't make Twitter...","negative"),
("i srsly hate stupid twitter API timeout thing, soooo annoying!!!!! :(","negative"),
("VIRAL MARKETING FAIL. ThAcia Pills brand oughta get shut down for hacking into people's messenger's.  get 5-6 msgs day! Arrrgh!","negative"),
("Night at Museum tonite instead of UP. :( oh well. that 4 yr old better enjoy it. LOL","negative"),
("It's unfortunate that after Stimulus plan was put place twice help GM on back of American people has led inevitable","negative"),
("Tell me again why giving more $$ GM?? should use that $ for all programs that support unemployed.","negative"),
("@jdreiss oh yes if GM dies will only be worth more boo hahaha","negative"),
("Time Warner cable down again 3rd time since Memorial Day bummer!","negative"),
("I would rather pay reasonable yearly taxes for \"free\" fast internet, than get gouged by Time Warner for slow connection.","negative"),
("NOOOOOOO my DVR just died was only half way through EA presser. Hate you Time Warner","negative"),
("F*ck Time Warner Cable!!! You f*cking suck balls!!! have $700 HD tv &amp; my damn HD channels hardly ever come in. Bullshit!!","negative"),
("time warner has worse customer service ever. will never use them again","negative"),
("Time warner devil. Worst possible time for Internet go out.","negative"),
("Fuck no internet damn time warner!","negative"),
("time warner really picks worst time not work. all want do get mtv.com so can watch hills. wtfffff.","negative"),
("I hate Time Warner! Soooo wish had Vios. Cant watch fricken Mets game w/o buffering. feel like im watching free internet porn.","negative"),
("Ahh...got rid of stupid time warner today &amp; now taking nap while roomies cook for me. Pretty good end for monday :)","negative"),
("Time Warner's HD line up crap.","negative"),
("being fucked by time warner cable. didnt know modems could explode. Susan Boyle sucks too!","negative"),
("Time Warner Cable slogan: Where calling day at 2pm Happens.","negative"),
("Recovering from surgery..wishing @julesrenner was here :(","negative"),
("THE DENTIST LIED! \" U WON'T FEEL ANY DISCOMORT! PROB WON'T EVEN NEED PAIN PILLS\" MAN U TWIPPIN THSHIT HURT!! HOW MANY PILLS CAN TAKE!!","negative"),
("@kirstiealley my dentist great she's expensive...=(","negative"),
("my dentist was wrong... WRONG","negative"),
("Going dentist later.:|","negative"),
("Son has me looking at cars online.  hate car shopping.  Would rather go dentist!  Anyone with good car at good price sell?","negative"),
("luke got stopped walking out of safeway asked empty our pockets lift our shirts. how jacked up that?","negative"),
("The safeway bathroom still smells like ass!","negative"),
("At safeway on elkhorn, move like they're dead!","negative"),
("Found NOTHING at Nike Factory :/ Off Banana Republic Outlet! http://myloc.me/2zic","negative"),
("Time Warner Road Runner customer support here absolutely blows. hate not having other high-speed net options. I'm ready go nuclear.","negative"),
("Time Warner cable phone reps r dumber than nails!!!!! UGH! Cable was working 10 mins ago now its not WTF!","negative"),
("@siratomofbones tried Time Warner wasn't being nice so recorded today. :)","negative"),
("OMG - time warner f'ed up my internet install - instead of today  its now NEXT saturday - another week w/o internet! &amp;$*ehfa^V9fhg[*# fml.","negative"),
("wth..i have never seen line thloooong at time warner before, ugh.","negative"),
("Impatiently awaiting arrival of time warner guy. It's way too pretty be inside all afternoon","negative"),
("Naive Bayes using EM for Text Classification. Really Frustrating...","negative"),
("@KarrisFoxy If you're being harassed by calls about your car warranty, changing your number won't fix that. call every number. #d-bags","negative"),
("Just blocked United Blood Services using Google Voice. call more than those Car Warranty guys.","negative"),
("#at&amp;t complete fail.","negative"),
("@broskiii OH SNAP YOU WORK AT AT&amp;T DON'T YOU","negative"),
("@Mbjthegreat really dont want AT&amp;T phone service..they suck when comes having signal","negative"),
("I say just cut out small talk: AT&amp;T's new slogan: F__k you, give us your money. (Apologies Bob Geldof.)","negative"),
("pissed about at&amp;t's mid-contract upgrade price for iPhone (it's $200 more) I'm not going pay $499 for something thought was $299","negative"),
("Safari 4 fast :) Even on my shitty AT&amp;T tethering.","negative"),
("@ims What AT&amp;T fucking up?","negative"),
("@springsingfiend @dvyers @sethdaggett @jlshack AT&amp;T dropped ball isn't supporting crap with new iPhone 3.0... FAIL #att SUCKS!!!","negative"),
("@MMBarnhill yay, glad you got phone! Still, damn you, AT&amp;T.","negative"),
("Talk Cheap: Bing that, I?ll stick with Google. http://bit.ly/XC3C8","negative"),
("@defsounds WTF point of deleting tweets if can still be found summize searches? Twitter, please fix that. Thanks bye","negative"),
("The real AIG scandal / http://bit.ly/b82Px","negative"),
("LEbron james got car accident guess..just heard on evening news...wow cant believe it..will he be ok ? http://twtad.com/69750","negative"),
("Kobe best world not lebron .","negative"),
("I have go Booz Allen Hamilton for 2hr meeting :(  then get go home :)","negative"),
("@ambcharlesfield lol. Ah my skin itchy :( damn lawnmowing.","negative"),
("itchy back!! dont ya hate it!","negative"),
("so tired. didn't sleep well at all last night.","negative"),
("Boarding plane for San Francisco 1 hour; 6 hr flight. Blech.","negative"),
("bonjour San Francisco. My back hurts from last night..","negative"),
("F*** up big, or go home - AIG","negative"),
("Malcolm Gladwell genius at tricking people into not realizing he's fucking idiot","negative"),
("@sportsguy33 hey no offense malcolm gladwell pretenious, annoying cunt he brings you down. cant read hshit","negative"),
("i hate comcast right now. everything down cable internet &amp; phone....ughh what am do","negative"),
("Comcast sucks.","negative"),
("The day never have deal with Comcast again will rank as one of best days of my life.","negative"),
("@Dommm did comcast fail again??","negative"),
("curses Twitter API limit","negative"),
("Now can see why Dave Winer screams about lack of Twitter API, its limitations access throttles!","negative"),
("Arg. Twitter API making me crazy.","negative"),
("#wolfram Alpha SUCKS! Even for researchers information provided less than you can get from #google or #wikipedia, totally useless!","negative"),
("@Fraggle312 oh those awesome! so wish weren't owned by nike :(","negative"),
("arhh, It's weka bug. = =\" spent almost two hours find that out. crappy me","negative"),
("Oooooooh... North Korea troubleeeee! http://bit.ly/19epAH","negative"),
("Wat heck North Korea doing!!??!! just conducted powerful nuclear tests! Follow link: http://www.msnbc.msn.com/id/30921379","negative"),
("Listening Obama... Friggin North Korea...","negative"),
("I just realized three monkeys white Obama.Biden,Pelosi . Sarah Palin 2012","negative"),
("@foxnews Pelosi should stay China never come back.","negative"),
("Nancy Pelosi gave worst commencement speech I've ever heard. Yes I'm still bitter about this","negative"),
("ugh. amount of times these stupid insects have bitten me. Grr..","negative"),
("Just got barraged by horde of insects hungry for my kitchen light. So scary.","negative"),
("Math review. Im going fail exam.","negative"),
("Colin Powell rocked yesterday on CBS. Cheney needs shut hell up go home.Powell man of Honor served our country proudly","negative"),
("obviously not siding with Cheney here: http://bit.ly/19j2d","negative"),
("saw night at museum out of sheer desperation. who funding these movies?","negative"),
("Back from seeing 'Star Trek' 'Night at Museum.' 'Star Trek' was amazing, 'Night at Museum' was; eh.","negative"),
("It shame about GM. What if forced make only cars White House THINKS will sell? What do you think?","negative"),
("As u may have noticed, not too happy about GM situation, nor AIG, Lehman, et al","negative"),
("@Pittstock $GM good riddance.  sad though.","negative"),
("I Will NEVER Buy Government Motors Vehicle: Until just recently, drove GM cars. Since 1988, when bought .. http://tinyurl.com/lulsw8","negative"),
("Having old Coca-Cola guy on GM board stupid has heck! #tcot #ala","negative"),
("#RantsAndRaves worst thing about GM (concord / pleasant hill / martinez): fucking UAW. ..   http://buzzup.com/4ueb","negative"),
("Give man fish, u feed him for day. Teach him fish, u feed him for life. Buy him GM, u F**K him over for good.","negative"),
("The more hear about thGM thing more angry get. Billions wasted, more bullshit. All for something like 40k employees all the..","negative"),
("@QuantTrader own GM car junk as far as quality compared honda","negative"),
("sad day...bankrupt GM","negative"),
("upset about whole GM thing. life as know so screwed up","negative"),
("whoever running time warner needs be repeatedly raped by rhino so understand consequences of putting out shitty cable svcs","negative"),
("#WFTB Joining bit late. My connection was down (boo time warner)","negative"),
("Cox or Time Warner?  Cox cheaper gets B on dslreports.  TW more expensive gets C.","negative"),
("i am furious with time warner their phone promotions!","negative"),
("Just got home from chick-fil-a with boys. Damn my internets down =( stupid time warner","negative"),
("could time-warner cable suck more?  NO.","negative"),
("Pissed at Time Warner for causin me have slow internet problems","negative"),
("@sportsguy33 Ummm, having some Time Warner problems?","negative"),
("You guys see this?  Why does Time Warner have suck so much ass?  Really wish could get U-Verse at my apartment. http://bit.ly/s594j","negative"),
("RT @sportsguy33 upside Time Warner: unhelpful phone operators   superslow on-site service. Crap, that's not an upside.","negative"),
("RT @sportsguy33: New Time Warner slogan: \"Time Warner, where make you long for days before cable.\"","negative"),
("confirmed: it's Time Warner's fault, not Facebook's, that fb taking about 3 minutes load. so tempted switch verizon =/","negative"),
("@sportsguy33 Time Warner = epic fail","negative"),
("I know. How sad that?  RT @caseymercier: 1st day of hurricane season. That's less scarey than govt taking over GM.","negative"),
("GM files Bankruptcy, not good sign...","negative"),
("I hate effing dentist.","negative"),
("@kirstiealley hate going dentist.. !!!","negative"),
("i hate dentist....who invented them anyways?","negative"),
("thdentist's office cold :/","negative"),
("@ Safeway. Place nightmare right now. Bumming.","negative"),
("HATE safeway select green tea icecream! bought two cartons, what waste of money.  &gt;_&lt;","negative"),
("argghhhh why won't  my jquery appear safari bad safari !!!","negative"),
("I can't watch TV without Tivo.  after all these years, Time/Warner DVR  STILL sucks. http://www.davehitt.com/march03/twdvr.html","negative"),
("I still love my Kindle2 reading New York Times on does not feel natural. miss Bloomingdale ads.","negative"),
("Although today's keynote rocked, for every great announcement, AT&amp;T shit on us just little bit more.","negative"),
("@sheridanmarfil - its not so much my obsession with cell phones, iphone!  i'm slave at&amp;t forever because of it. :)","negative"),
("Fuzzball more fun than AT&amp;T ;P http://fuzz-ball.com/twitter","negative"),
("Today good day dislike AT&amp;T. Vote out of office indeed, @danielpunkass","negative"),
("looks like summize has gone down. too many tweets from WWDC perhaps?","negative"),
("Man kinda dislike Apple right now. Case point: iPhone 3GS. Wish there was video recorder app. Please?? http://bit.ly/DZm1T","negative"),
("dearest @google, you rich bastards! VISA card you sent me doesn't work. why screw little guy like me?","negative"),
("Fighting with LaTex. Again...","negative"),
("@Iheartseverus love you too don't want you die!!!!!!  Latex = devil","negative"),
("7 hours. 7 hours of inkscape crashing, normally solid as rock. 7 hours of LaTeX complaining at slightest thing. can't take any more.","negative"),
("Shit's hitting fan Iran...craziness indeed #iranelection","negative"),
("Monday already. Iran may implode. Kitchen disaster. @annagoss seems happy. @sebulous had nice weekend @goldpanda great. whoop.","negative"),
("I just created my first LaTeX file from scratch. That didn't work out very well. (See @amandabittner , it's great time waster)","negative"),
("On that note, hate Word. hate Pages. hate LaTeX. There, said it. hate LaTeX. All you TEXN3RDS can come kill me now.","negative"),
("Trouble Iran, see. Hmm. Iran. Iran so far away. #flockofseagullsweregeopoliticallycorrect","negative"),
("Reading tweets coming out of Iran... whole thing terrifying incredibly sad...","negative")
]